#!/bin/bash


# cosmetics.
rm *~
rm \#*
rm *\#


dirs=('bootstrap' 'books' 'calendars' 'usr' 'z4' 'lib' 'bin' 'views' 'public' 'media' 'db' 'ledger' 'records');
_i='PryOn';

Z4_VLC_RPC="--extraintf rc --rc-host 127.0.0.1:9595";

Z4_VLC_STREAM=":screen-fps=30 :screen-caching=100 --sout '#transcode{vcodec=mp4v,vb=4096,acodec=mpga,ab=256,scale=1,width=1024,height=768‌​}:standard{access=http, mux=ts, dst=:8080}'"

function sec() {
    echo "###### [$_i][$1]";
}
function log() {
    echo -e "#----- [$_i][$1] $2";
}


source release.sh

source env.sh

sec 'vlc'

log 'vlc' 'beginning stream'
# video streaming server.  makes anything played through the vlc server over http
cvlc $Z4_VLC_RPC $Z4_VLC_STREAM &
log 'vlc' 'stream available'


sec 'sanity'
log 'sanity' 'creating directories'
for d in $dirs
do
   mkdir -p $d  
done

log 'sanity' 'directories created'
for d in $dirs
do
    rm $d/*~ > /dev/null 1>&1
    rm $d/#* > /dev/null 2>&1
    rm $d/*# > /dev/null 2>&1
done

sec 'bootstrap'

if [[ "$1" == "bootstrap" ]]; then
    log 'bootstrap' 'beginning...'
   for f in bootstrap/*.sh
   do       
     chmod +x $f;
     ./$f;
   done
   log 'bootstrap' 'ready!'
fi

sec 'rake'

rake

sec 'console'

ruby bin/console
